.TH MYSTRNCPY 1 "September 2026" "MyUtils" "User Commands"
.SH NAME
mystrncpy \- copy a limited number of characters
.SH SYNOPSIS
.B mystrncpy
.BI "char *dest, const char *src, size_t n"
.SH DESCRIPTION
The mystrncpy function copies up to n characters from the source
string to the destination string.
.SH AUTHOR
Eras Tariq
