.TH MYSTRCPY 1 "September 2026" "MyUtils" "User Commands"
.SH NAME
mystrcpy \- copy a string
.SH SYNOPSIS
.B mystrcpy
.BI "char *dest, const char *src"
.SH DESCRIPTION
The mystrcpy function copies the contents of the source string
into the destination string, including the terminating null character.
.SH AUTHOR
Eras Tariq
